services:
  - type: web
    name: nt-pulse-orchestrator
    env: node
    plan: free
    buildCommand: "npm install --include=dev && npm run build"
    startCommand: "node dist/orchestrator.js"
    envVars:
      - key: NODE_ENV
        value: production

      - key: ORCHESTRATION_SECRET
        value: "generate-a-long-random-string-here-12345"

  - type: web
    name: nt-pulse-edge-1
    env: node
    plan: free
    buildCommand: "npm install --include=dev && npm run build"
    startCommand: "node dist/server.js"
    envVars:
      - key: NODE_ENV
        value: production

      - key: ORCHESTRATION_SECRET
        value: "generate-a-long-random-string-here-12345"
      - key: ORCHESTRATION_HOST
        value: "http://nt-pulse-orchestrator:4000"
        fromService:
          type: web
          name: nt-pulse-orchestrator
          envVarKey: RENDER_EXTERNAL_URL
